// Code generated by docs/contracts/generate.mjs; DO NOT EDIT.

package schema

import "embed"

// Files contains the byte-for-byte approved JSON Schema snapshots.
//
//go:embed *.schema.json
var Files embed.FS

func Read(name string) ([]byte, error) {
	return Files.ReadFile(name)
}
